### ISSUE TITLE
Implement independent chat app

### ISSUE THREAD

**Issue by PinGunter** [Anatoli-Grishenko/es.ugr.larva.core#6]
As we discussed in Telegram, the chat view is currently attached to the exercises. If possible, an independent app would ease the use of this functionality.

**Comment by Anatoli-Grishenko** [comment]
Thanks @PinGunter for your proposal. Since problems with Telegram seem to be solved (by the time of writing this) this project will be suspended.

**Comment by Anatoli-Grishenko** [comment]
So ...
